version: "3.7"

services:
  myapi:
    container_name: myapi
    restart: always
    image: node:16.13.2-alpine
    working_dir: /usr/src/app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    command: npm run start:dev
    env_file: .env
    init: true
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql

  mysql:
    image: bitnami/mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: ${MYSQL_AUTHENTICATION_PLUGIN}
    volumes:
      - mysqldata:/bitnami/mysql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  mysqldata:
    driver: local
